### ISSUE TITLE
Fix flashing when adding nodes

### ISSUE THREAD

**Issue by ishanpm** [ishanpm/chemlambda-editor#2]
It's fixed here https://mbuliga.github.io/feed-the-quine.html by adding an extremely short fade-in, but I think there might be a way to have the nodes simply appear where they're supposed to be.

**Comment by mbuliga** [comment]
Agree! Incidentally an interesting unexpected visual effect if you comment line 232 duration(1) and you uncomment/replace it by delay(1) or even delay(5).
